version: "3.2"
services:
  ibizpms-provider-webapi:
    image: registry.cn-shanghai.aliyuncs.com/ibizsys/ibizpms-provider-webapi:latest
    ports:
      - "32011:32011"
      - "9988:9988"
    networks:
      - agent_network
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.16.240.110
      - SERVER_PORT=32011
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=172.16.240.110:8850
      - SPRING_REDIS_HOST=172.16.240.110
      - SPRING_REDIS_PORT=6381
      - SPRING_REDIS_DATABASE=0
      - SPRING_DATASOURCE_USERNAME=a_A_23e8aa361
      - SPRING_DATASOURCE_PASSWORD=b7989eb@
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.16.180.232:3306/a_A_23e8aa361?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_DEFAULTSCHEMA=a_A_23e8aa361
      - PORTMAP=9988:9988
      - ZUUL_ROUTES_IBZEMP_SERVICEID=ibizpms-webapi
      - IBIZ_AUTH_LADP=true
      - JOBS_APP-PORT=9988
      - CAS=https://passport.ibizlab.cn
      - NACOS=172.16.240.110:8850
      - IBIZ_CACHELEVEL=L2
      - SEATA_REGISTRY_NACOS_SERVER-ADDR=172.16.240.110:8850
      - SEATA_ENABLED=true
    deploy:
      resources:
           limits:
               memory: 4048M
           reservations:
               memory: 400M    
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    volumes:
      - "nfs:/app/file"

volumes:
  nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=172.16.240.109,rw"
      device: ":/nfs"

networks:
  agent_network:
    driver: overlay
    attachable: true

