version: "3.2"
services:
  ibizpms-app-web:
    image: registry.cn-shanghai.aliyuncs.com/ibizsys/ibizpms-app-web:latest
    ports:
      - "22150:22150"
    networks:
      - agent_network
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.16.240.110
      - SERVER_PORT=22150
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=172.16.240.110:8848
      - SPRING_REDIS_HOST=172.16.240.110
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_DATABASE=0
      - SPRING_DATASOURCE_USERNAME=zentao
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.16.180.217:3306/zentao?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_DEFAULTSCHEMA=zentao
      - REMOTEDYNAPATH=http://172.16.240.51/dynamic_demo/1688344C-3A57-44BD-B135-249E24FCE4F6/
      - CAS=https://passport.ibizlab.cn
      - NACOS=172.16.240.110:8848
      - BDYNAMIC=false
      - SEATA_REGISTRY_NACOS_SERVER-ADDR=172.16.240.110:8848
      - SEATA_ENABLED=true
    deploy:
      resources:
           limits:
               memory: 800M
           reservations:
               memory: 400M    
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    volumes:
      - "nfs:/app/file"

volumes:
  nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=172.16.240.109,rw"
      device: ":/nfs"

networks:
  agent_network:
    driver: overlay
    attachable: true

