---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibizpms-app-mob
  labels:
    app: ibizpms-app-mob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibizpms-app-mob
  template:
    metadata:
      labels:
        app: ibizpms-app-mob
    spec:
      imagePullSecrets:
      - name: aly-shanghai
      containers:
      - name: ibizpms-app-mob
        image: registry.cn-shanghai.aliyuncs.com/ibizsys/ibizpms-app-mob:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 22120
        env:
        - name: SPRING_CLOUD_NACOS_DISCOVERY_IP
          value: "172.16.240.110"      
        - name: SERVER_PORT
          value: "22120"
        - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR
          value: "172.16.240.110:8848"
        - name: SPRING_REDIS_HOST
          value: "172.16.240.110"
        - name: SPRING_REDIS_PORT
          value: "6379"
        - name: SPRING_REDIS_DATABASE
          value: "0"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "123456"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://127.0.0.1:3306/iBizPMS?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&allowMultiQueries=true"
        - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
          value: "com.mysql.jdbc.Driver"
        - name: SPRING_DATASOURCE_DEFAULTSCHEMA
          value: "root"
        - name: REMOTEDYNAPATH
          value: "http://172.16.240.51/dynamic_demo/1688344C-3A57-44BD-B135-249E24FCE4F6/"      
        - name: CAS
          value: "https://passport.ibizlab.cn"      
        - name: NACOS
          value: "172.16.240.110:8848"      
        - name: BDYNAMIC
          value: "false"      
        - name: SEATA_REGISTRY_NACOS_SERVER-ADDR
          value: "172.16.240.110:8848"      
        - name: SEATA_ENABLED
          value: "true"      
        volumeMounts:
        - name: data
          mountPath: /app/file
      volumes:      
      - name: data
        persistentVolumeClaim:
          claimName: demo-date-pvc-nfs

---
apiVersion: v1
kind: Service
metadata:
  name: ibizpms-app-mob
  labels:
    app: ibizpms-app-mob
spec:
  type: NodePort
  ports:
  - name: http
    port: 22120
    targetPort: 22120
    nodePort: 22120
    protocol: TCP
  selector:
    app: ibizpms-app-mob

